main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('workouts/', views.workouts_index, name='index'),
    path('workouts/<int:workout_id>/', views.workouts_detail, name='detail'),
    path('workouts/create/', views.WorkoutCreate.as_view(), name='workouts_create'),
    path('workouts/<int:pk>/update/', views.WorkoutUpdate.as_view(), name='workouts_update'),
    path('workouts/<int:pk>/delete/', views.WorkoutDelete.as_view(), name='workouts_delete'),
    path('workouts/<int:workout_id>/logging/', views.logging, name='logging'),
    path('exercises/create/', views.ExerciseCreate.as_view(), name='exercises_create'),
    path('exercises/', views.ExerciseIndex.as_view(), name='exercises_index'),
    path('exercises/<int:pk>/', views.ExerciseDetail.as_view(), name='exercises_detail'),
    path('exercises/<int:pk>/update/', views.ExerciseUpdate.as_view(), name='exercises_update'),
    path('exercises/<int:pk>/delete/', views.ExerciseDelete.as_view(), name='exercises_delete'),
    path('workouts/<int:workout_id>/add_exercise/<int:exercise_id>/', views.add_exercise, name='add_exercise'),
    path('workouts/<int:workout_id>/remove_exercise/<int:exercise_id>/', views.remove_exercise, name='remove_exercise'),
    # path('loggings/create/', views.LoggingCreate.as_view(), name='loggings_create'),
    # path('loggings/', views.ExerciseIndex.as_view(), name='loggings_index'),
    # path('loggings/<int:pk>/', views.ExerciseDetail.as_view(), name='loggings_detail'),
    # path('loggings/<int:pk>/update/', views.ExerciseUpdate.as_view(), name='loggings_update'),
    # path('loggings/<int:pk>/delete/', views.ExerciseDelete.as_view(), name='loggings_delete'),
    # path('workouts/<int:workout_id>/add_logging/<int:logging_id>/', views.add_logging, name='add_logging'),
    # path('workouts/<int:workout_id>/remove_logging/<int:logging_id>/', views.remove_logging, name='remove_logging'),
    path('accounts/signup/', views.signup, name='signup'),
]

workouttracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

class Exercise(models.Model):
    name = models.CharField(max_length=100)
    sets = models.IntegerField()
    reps = models.IntegerField()
    weight = models.IntegerField()

    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse('exercises_detail', kwargs={'pk': self.id})

class Workout(models.Model):
    name = models.CharField(max_length=100)
    target = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    exercises = models.ManyToManyField(Exercise)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'workout_id': self.id})

class Logging(models.Model):
    EFFORTS = (
        ('*', '1 Star'),
        ('**', '2 Star'),
        ('***', '3 Star'),
        ('****', '4 Star'),
        ('*****', '5 Star'),
    )
    date = models.DateField('workout date')
    effort = models.CharField(max_length=5, choices=EFFORTS, default=EFFORTS[0][0], verbose_name='effort given')
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_effort_display()} on {self.date}"

    class Meta:
        ordering = ('-date',)

main_app/forms.py
from django.forms import ModelForm
from .models import Logging

class LoggingForm(ModelForm):
    class Meta:
        model = Logging
        fields = ['date', 'effort']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView, DetailView
from .models import Workout, Exercise
from .forms import LoggingForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def workouts_index(request):
    workouts = Workout.objects.filter(user=request.user)
    return render(request, 'workouts/index.html', { 'workouts': workouts })

@login_required
def workouts_detail(request, workout_id):
    workout = Workout.objects.get(id=workout_id)
    logging_form = LoggingForm()
    # loggings_workout_dn_have = Logging.objects.exclude(id__in=workout.exercises.all().values_list('id'))
    exercises_workout_dn_have = Exercise.objects.exclude(id__in=workout.exercises.all().values_list('id'))
    return render(request, 'workouts/detail.html', {
        'workout': workout,
        'logging_form': logging_form,
        'exercises': exercises_workout_dn_have
    })

@login_required
def logging(request, workout_id):
  form = LoggingForm(request.POST)
  if form.is_valid():
    new_logging = form.save(commit=False)
    new_logging.workout_id = workout_id
    new_logging.save()
  return redirect('detail', workout_id=workout_id)

# @login_required
# def add_logging(request, workout_id):
#   Workout.objects.get(id=workout_id).logging.add(logging_id)
#   return redirect ('detail', workout_id=workout_id)

# @login_required
# def remove_logging(request, workout_id, logging_id):
#   Workout.objects.get(id=workout_id).logging.remove(logging_id)
#   return redirect('detail', workout_id=workout_id)

@login_required
def add_exercise(request, workout_id, exercise_id):
  Workout.objects.get(id=workout_id).exercises.add(exercise_id)
  return redirect('detail', workout_id=workout_id)

@login_required
def remove_exercise(request, workout_id, exercise_id):
  Workout.objects.get(id=workout_id).exercises.remove(exercise_id)
  return redirect('detail', workout_id=workout_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    pass
  form = UserCreationForm(request.POST)
  if form.is_valid():
    user = form.save()
    login(request, user)
    return redirect('index')
  else:
    error_message = 'invalid credentials'
    form = UserCreationForm()
  return render(request, 'registration/signup.html', {
    'form': form,
    'error_message': error_message
  })

class WorkoutCreate(LoginRequiredMixin, CreateView):
  model = Workout
  fields = ('name', 'target', 'description')
  success_url = '/workouts/'

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class WorkoutUpdate(LoginRequiredMixin, UpdateView):
  model = Workout
  fields = ('name', 'target', 'description')

class WorkoutDelete(LoginRequiredMixin, DeleteView):
  model = Workout
  success_url = '/workouts/'

class ExerciseIndex(LoginRequiredMixin, ListView):
  model = Exercise

class ExerciseDetail(LoginRequiredMixin, DetailView):
  model = Exercise

class ExerciseCreate(LoginRequiredMixin, CreateView):
  model = Exercise
  fields = '__all__'
  success_url = '/exercises/'

class ExerciseUpdate(LoginRequiredMixin, UpdateView):
  model = Exercise
  fields = '__all__'

class ExerciseDelete(LoginRequiredMixin, DeleteView):
  model = Exercise
  success_url = '/exercises/'

# class LoggingIndex(LoginRequiredMixin, ListView):
#   model = Logging
#   fields = ('date', 'effort')
#   success_url = '/loggings/'

# class LoggingDetail(LoginRequiredMixin, DetailView):
#   model = Logging

# class LoggingCreate(LoginRequiredMixin, CreateView):
#   model = Logging
#   fields = ('date', 'effort')
#   success_url = '/loggings/'

# class LoggingUpdate(LoginRequiredMixin, UpdateView):
#   model = Logging
#   fields = '__all__'

# class LoggingDelete(LoginRequiredMixin, DeleteView):
#   model = Logging
#   success_url = '/loggings/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block mainclass %}
aboutBackground
{% endblock %}
{% block content %}

<div class="newMain">
    <div class="addWorkout">
        <h1 class="center-align">About LifTrackr</h1>
        <h5 class="center-align">Mobile friendly workout tracker designed for simplicity of records. Quickly create an account and start uploading all of your current exercises. Once you have a strong list compiled, you can add these exercises to any of your workout routines. Post workout, athletes can record the date and effort attributed to the workout.</h5>
    </div>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>LifTrackr</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper teal darken-3">
        <a href="/" class="left-brand-logo"> LifTrackr</a>
        <img src="/static/images/weightlogo.svg" class="rotate" alt="weight" width="50px" height="50px">
        <ul class="right">
          <li class="lime darken-3"><a href="/about">About</a></li>
          {% if user.is_authenticated %}
          <li class="lime darken-3"><a href="{% url 'workouts_create' %}">Create Workout</a></li>
          <li class="lime darken-3"><a href="{% url 'index' %}">View My Routines</a></li>
          <li class="lime darken-3"><a href="{% url 'exercises_create' %}">Add Exercise</a></li>
          <li class="lime darken-3"><a href="{% url 'exercises_index' %}">View All Exercises</a></li>
          <li class="lime darken-3"><a href="{% url 'logout' %}">Log Out</a></li> 
          {% else %} 
          {% comment %} <li><a href="{% url 'login' %}">Log In</a></li>  {% endcomment %}
          {% comment %} <li><a href="{% url 'signup' %}">Signup</a></li>  {% endcomment %}
          {% endif %}  
        </ul>
      {% comment %} </div> {% endcomment %}
    </div>
    </nav>
  </header>
  <main class="{% block mainclass %}{% endblock %}">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer teal darken-3">
    <div class="footer">
      All Rights Reserved, © 2023 LifTrackr
      <a href="/admin">Admin</a>
    </div>
  </footer>
</body>

</html>

main_app/templates/home.html
{%  extends 'base.html' %} 

{% block mainclass %}
homeBackground
{% endblock %}

{% block content %}
<div class="homePage">
    <div class="leftside">
    </div>
    <div class="rightside">
        <div class="homeBodyContainer">
            <h1 class="center-align"> Enter </h1>
            <div class="loginSignup">
            <a class="btn btn-large lime " href="{% url 'login' %}">Log In</a>
            <a class="btn btn-large lime " href="{% url 'signup' %}">Signup</a>
        </div>
    </div>
</div>



{% endblock %}s

main_app/templates/main_app/exercise_confirm_delete.html
{% extends 'base.html' %} 

{% block content %}
<h1>Delete Exercise</h1>

<h4>
  Are you sure you want to delete <span class="card-title">A <span class="{{ exercise.name }}-text">{{ exercise.target.capitalize }}</span>
  </span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete" class="btn" />
  <a href="{% url 'Exercises_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/exercise_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Exercise Details</h1>

<div class="card lime lighten-2">
    <a href="{% url 'exercises_detail' exercise.id %}">
        <div class="card-content grey darken-3">
            <span class="card-title">
                <span> {{ exercise.name }}, {{ exercise.target.capitalize }}</span>
                    <p>Sets:{{exercise.sets}} Reps:{{ exercise.reps }}</p>
        </div>
    </a>
    <div class="card-action">
        <a href="{% url 'exercises_update' exercise.id %}">Edit</a>
        <a href="{% url 'exercises_delete' exercise.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/main_app/exercise_form.html
{% extends 'base.html' %}

{% block content%}

<div class="newMain">
<div class="addExercise">
    <form action='' method='POST' autocomplete="off">
        {% csrf_token %}
        {% if object %}
        <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
        {% else %}
        <h1>Add Exercise</h1>
        {% endif%}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn" />
    </form>
</div>
</div>

{% endblock%}

main_app/templates/main_app/exercise_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Exercises to choose from</h1>

{% for exercise in object_list %}
<div class="card lime lighten-2">
  <a href="{% url 'exercises_detail' exercise.id %}" >
    <div class="card-content grey darken-3">
    <span class="card-title"> 
      <span> {{ exercise.name }} </span>
  </div>
  </a>
</div>

{% endfor %} 

{% endblock %}

main_app/templates/main_app/workout_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Routine?</h1>

<h4>
  Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' workout.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/workout_form.html
{% extends 'base.html' %}

{% block content%}

<div class="newMain">
<div class="addWorkout">
    <form action='' method='POST' autocomplete="off">
        {% csrf_token %}
        {% if object %}
        <h1> Edit <span class="teal-text">{{ object.name }}</span></h1>
        {% else %}
        <h1>Add Workout</h1>
        {% endif%}
        <table>
           {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" class="btn" />
    </form>
</div>
</div>
{% endblock %}

main_app/templates/workouts/detail.html
{% extends 'base.html' %}

{% block content %}

<h1 class="center-align">Routine Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card lime lighten-2">
      <div class="card-content grey darken-3">
        <span class="card-title">{{ workout.name }}</span>
        <p>Target Muscles: {{ workout.target }}</p>
        <p>Description: {{ workout.description }}</p>
      </div>
        <div class="card-action">
          <a href="{% url 'workouts_update' workout.id %}">Edit</a>
          <a href="{% url 'workouts_delete' workout.id %}">Delete</a>
        </div>
      </div>
  <div class="col s6">
    <form action="{% url 'logging' workout.id %}" method="POST">
      {% csrf_token %}
      {{ logging_form.as_p }}
      <input type="submit" value="Record Workout" class="btn">
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Effort</th>
        </tr>
      </thead>
      <tbody>
        {% for logging in workout.logging_set.all %}
          <tr>
            <td>{{ logging.date }}</td>
            <td>{{ logging.get_effort_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<div class="row">
  <div class="col s6">
    <h3>{{ workout.name }} contains...</h3>
    {% if workout.exercises.count %}
      {% for exercise in workout.exercises.all %}
      <div class="card lime lighten-2">
        <div class="card-content grey darken-3">
          <span class="card-title">
            <span class="{{ exercise.sets.lower }}-text">{{ exercise.sets }}</span> {{ exercise.name }}
            <form action="{% url 'remove_exercise' workout.id exercise.id %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="Remove" class="btn">
            </form>
          </span>
        </div>
      </div>
      {% endfor %}
    {% else %}
        <h5>{{ workout.name }} doesn't have associated exercises yet!</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Exercises</h3>
    {% if exercises.count %}
      {% for exercise in exercises %}
      <div class="card lime lighten-2">
        <div class="card-content grey darken-3">
            <span class="card-title">
              <span>{{ exercise.name }}</span>
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'add_exercise' workout.id exercise.id %}" method="POST">
              {% csrf_token %}
              <input type="submit" value="Add" class="btn">
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
    <h5>{{ workout.name }} Already Has All Exercises Currently Available</h5>
    {% endif %}
  </div>
</div>

<script>
// materialize form widget config
const dateEl = document.getElementById('id_date');
M.Datepicker.init(dateEl, {
  format: 'yyyy-mm-dd',
  defaultDate: new Date(),
  setDefaultDate: true,
  autoClose: true
});

const selectEl = document.getElementById('id_effort');
M.FormSelect.init(selectEl);

</script>

{% endblock %}

main_app/templates/workouts/index.html
{% extends 'base.html' %} 

{% block content %}

<h1>Workout List</h1>

{% for workout in workouts %}
<div class="card lime lighten-2">
  <a href="{% url 'detail' workout.id %}">
    <div class="card-content grey darken-3">
    <span class="card-title">{{ workout.name }}</span>
    <p>Target Muscles: {{ workout.target }}</p>
    <p>Description: {{ workout.description }}</p>
  </div>
</a>
</div>
{% endfor %} 

{% endblock %}